## NumPy Arrays

In [2]:
import numpy as np

myList = [1,2,3]

np.array(myList)

array([1, 2, 3])

In [3]:
type(myList)

list

In [4]:
my_math = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 13, 2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [11]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [15]:
np.eye(1001)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

### Random Arrays

In [17]:
np.random.rand(5)

array([0.83571905, 0.51736023, 0.39425538, 0.6452438 , 0.33437006])

In [25]:
np.random.rand(5,5)

array([[0.85839488, 0.14845667, 0.65292924, 0.97439174, 0.25769731],
       [0.01665465, 0.56681273, 0.60377559, 0.66708128, 0.66914886],
       [0.26095709, 0.55796571, 0.28376408, 0.56316946, 0.4203946 ],
       [0.75090458, 0.01904513, 0.88555476, 0.89680136, 0.52641127],
       [0.34230328, 0.14341862, 0.82718991, 0.20779802, 0.42081917]])

In [26]:
np.random.randn(4)

array([-0.77233826, -0.59387066, -0.38708528,  0.88259673])

In [28]:
 np.random.randint(1, 100, 24)


array([28, 20, 86, 49, 54,  3, 93, 89,  2, 54, 57, 26, 25, 22, 17, 90, 12,
       95, 22, 55, 83, 35,  3, 40])

In [39]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([26, 27, 33, 24, 48, 26, 37,  7, 19, 10])

In [42]:
arr.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [45]:
arr.max()

19

In [46]:
arr.min()

0

In [47]:
ranarr.max()

48

In [48]:
ranarr

array([26, 27, 33, 24, 48, 26, 37,  7, 19, 10])

In [49]:
ranarr.argmax()

4

In [51]:
ranarr.shape

(10,)

In [52]:
arr.shape

(20,)

In [54]:
arr = arr.reshape(5,4)

In [55]:
arr.shape

(5, 4)

In [56]:
arr.dtype

dtype('int32')

In [57]:
from numpy.random import randint

In [58]:
randint(1,10,5)

array([7, 1, 7, 4, 5])

### Indexing and Selection on NumPy Arrays

In [60]:
arr = np.arange(1,10)

In [61]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[:4]

array([1, 2, 3, 4])

In [67]:
arr[1:5:2]

array([2, 4])

In [68]:
arr[4:]

array([5, 6, 7, 8, 9])

In [69]:
arr[-1]

9

In [70]:
arr[-4]

6

In [72]:
arr[0:5] = 100

In [77]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [78]:
arr = np.arange(0, 25)

In [79]:
slice_arr = arr[0:5]

In [81]:
slice_arr

array([0, 1, 2, 3, 4])

In [90]:
slice_arr[:] = 33333

In [91]:
arr

array([33333, 33333, 33333, 33333, 33333,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24])

In [92]:
arr_copy = arr.copy()

In [93]:
arr

array([33333, 33333, 33333, 33333, 33333,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24])

In [94]:
arr_copy

array([33333, 33333, 33333, 33333, 33333,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24])

In [95]:
arr_copy[0:5] = 999

In [96]:
arr

array([33333, 33333, 33333, 33333, 33333,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24])

In [97]:
arr_copy

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

### 2D Arrray

In [99]:
arr_2d = np.array([[5,10,15], [23,44,1], [34,40,45]])

In [100]:
arr_2d

array([[ 5, 10, 15],
       [23, 44,  1],
       [34, 40, 45]])

In [106]:
arr_2d[1]

array([23, 44,  1])

In [108]:
arr_2d[2,1]

40

In [112]:
arr_2d[:, 1]

array([10, 44, 40])

In [114]:
arr_2d[:2, 1:]

array([[10, 15],
       [44,  1]])

In [115]:
arr_2d[2,1:]

array([40, 45])

In [127]:
arr = np.random.randint(1,15, 10)
arr

array([ 4, 11,  3,  1,  9,  9,  4,  2,  1,  7])

In [128]:
arr > 4

array([False,  True, False, False,  True,  True, False, False, False,
        True])

In [129]:
arr[arr>4]

array([11,  9,  9,  7])

In [131]:
arr[arr>8]

array([11,  9,  9])

In [134]:
ar_2d  = np.arange(50).reshape(5,10)

In [135]:
arr_2d

array([[ 5, 10, 15],
       [23, 44,  1],
       [34, 40, 45]])